// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	LoginReq
	LoginRsp
	PlayerAttr
	EnterGameNtf
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登录请求
// MsgId = 10001
type LoginReq struct {
	Uid     string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Nick    string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	Channel string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginReq) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *LoginReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

// 登录返回
// MsgId = 50001
type LoginRsp struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

// 玩家属性
type PlayerAttr struct {
	Attrs map[string]string `protobuf:"bytes,1,rep,name=attrs" json:"attrs,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PlayerAttr) Reset()                    { *m = PlayerAttr{} }
func (m *PlayerAttr) String() string            { return proto.CompactTextString(m) }
func (*PlayerAttr) ProtoMessage()               {}
func (*PlayerAttr) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PlayerAttr) GetAttrs() map[string]string {
	if m != nil {
		return m.Attrs
	}
	return nil
}

// 进入游戏通知
// MsgId = 50001
type EnterGameNtf struct {
	Players []*PlayerAttr `protobuf:"bytes,1,rep,name=players" json:"players,omitempty"`
	Token   string        `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *EnterGameNtf) Reset()                    { *m = EnterGameNtf{} }
func (m *EnterGameNtf) String() string            { return proto.CompactTextString(m) }
func (*EnterGameNtf) ProtoMessage()               {}
func (*EnterGameNtf) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *EnterGameNtf) GetPlayers() []*PlayerAttr {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *EnterGameNtf) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "msg.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "msg.LoginRsp")
	proto.RegisterType((*PlayerAttr)(nil), "msg.PlayerAttr")
	proto.RegisterType((*EnterGameNtf)(nil), "msg.EnterGameNtf")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x90, 0x51, 0x4b, 0xfb, 0x30,
	0x14, 0xc5, 0xe9, 0xfa, 0xef, 0xf6, 0xdf, 0x55, 0x50, 0x2e, 0x22, 0x61, 0x4f, 0xa3, 0x4f, 0xf3,
	0xa5, 0x88, 0x82, 0x0c, 0xdf, 0x7c, 0x18, 0x82, 0x88, 0x4a, 0xbe, 0x41, 0xec, 0xae, 0xb5, 0xb4,
	0x4d, 0x6a, 0x72, 0x2b, 0xf6, 0xdb, 0x4b, 0xb2, 0x86, 0x81, 0x2f, 0xe5, 0x9c, 0x73, 0x9b, 0xdf,
	0xc9, 0x0d, 0x2c, 0x3b, 0x57, 0x15, 0xbd, 0x35, 0x6c, 0x30, 0xed, 0x5c, 0x95, 0x3f, 0xc1, 0xff,
	0x67, 0x53, 0xd5, 0x5a, 0xd2, 0x17, 0x9e, 0x43, 0x3a, 0xd4, 0x7b, 0x91, 0xac, 0x93, 0xcd, 0x52,
	0x7a, 0x89, 0x08, 0xff, 0x74, 0x5d, 0x36, 0x62, 0x16, 0xa2, 0xa0, 0x51, 0xc0, 0xa2, 0xfc, 0x54,
	0x5a, 0x53, 0x2b, 0xd2, 0x10, 0x47, 0x9b, 0xdf, 0x45, 0x96, 0xeb, 0xfd, 0xc9, 0xd2, 0xec, 0x29,
	0xc0, 0x32, 0x19, 0x34, 0x5e, 0xc2, 0xdc, 0x92, 0x1b, 0x5a, 0x9e, 0x78, 0x93, 0xcb, 0x7f, 0x00,
	0xde, 0x5a, 0x35, 0x92, 0x7d, 0x60, 0xb6, 0x78, 0x0d, 0x99, 0x62, 0xb6, 0x4e, 0x24, 0xeb, 0x74,
	0x73, 0x72, 0xb3, 0x2a, 0xfc, 0x8d, 0x8f, 0xf3, 0xc2, 0x7f, 0xdc, 0x4e, 0xb3, 0x1d, 0xe5, 0xe1,
	0xc7, 0xd5, 0x16, 0xe0, 0x18, 0xfa, 0x2d, 0x1a, 0x1a, 0xe3, 0x16, 0x0d, 0x8d, 0x78, 0x01, 0xd9,
	0xb7, 0x6a, 0x07, 0x9a, 0x6a, 0x0f, 0xe6, 0x7e, 0xb6, 0x4d, 0xf2, 0x57, 0x38, 0xdd, 0x69, 0x26,
	0xfb, 0xa8, 0x3a, 0x7a, 0xe1, 0x0f, 0xbc, 0x82, 0x45, 0x1f, 0x9a, 0x62, 0xfb, 0xd9, 0x9f, 0x76,
	0x19, 0xe7, 0x1e, 0xca, 0xa6, 0x21, 0x1d, 0xa1, 0xc1, 0xbc, 0xcf, 0xc3, 0xd3, 0xde, 0xfe, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x58, 0x91, 0x53, 0xa4, 0x67, 0x01, 0x00, 0x00,
}
