// Code generated by protoc-gen-go. DO NOT EDIT.
// source: msg.proto

/*
Package msg is a generated protocol buffer package.

It is generated from these files:
	msg.proto

It has these top-level messages:
	LoginReq
	LoginRsp
*/
package msg

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// 登录请求
// MsgId = 10001
type LoginReq struct {
	Uid     string `protobuf:"bytes,1,opt,name=uid" json:"uid,omitempty"`
	Nick    string `protobuf:"bytes,2,opt,name=nick" json:"nick,omitempty"`
	Channel string `protobuf:"bytes,3,opt,name=channel" json:"channel,omitempty"`
}

func (m *LoginReq) Reset()                    { *m = LoginReq{} }
func (m *LoginReq) String() string            { return proto.CompactTextString(m) }
func (*LoginReq) ProtoMessage()               {}
func (*LoginReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LoginReq) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *LoginReq) GetNick() string {
	if m != nil {
		return m.Nick
	}
	return ""
}

func (m *LoginReq) GetChannel() string {
	if m != nil {
		return m.Channel
	}
	return ""
}

// 登录返回
// MsgId = 50001
type LoginRsp struct {
	Code   int32  `protobuf:"varint,1,opt,name=code" json:"code,omitempty"`
	Result string `protobuf:"bytes,2,opt,name=result" json:"result,omitempty"`
}

func (m *LoginRsp) Reset()                    { *m = LoginRsp{} }
func (m *LoginRsp) String() string            { return proto.CompactTextString(m) }
func (*LoginRsp) ProtoMessage()               {}
func (*LoginRsp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LoginRsp) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *LoginRsp) GetResult() string {
	if m != nil {
		return m.Result
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginReq)(nil), "msg.LoginReq")
	proto.RegisterType((*LoginRsp)(nil), "msg.LoginRsp")
}

func init() { proto.RegisterFile("msg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 135 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xcc, 0x2d, 0x4e, 0xd7,
	0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0xce, 0x2d, 0x4e, 0x57, 0xf2, 0xe2, 0xe2, 0xf0, 0xc9,
	0x4f, 0xcf, 0xcc, 0x0b, 0x4a, 0x2d, 0x14, 0x12, 0xe0, 0x62, 0x2e, 0xcd, 0x4c, 0x91, 0x60, 0x54,
	0x60, 0xd4, 0xe0, 0x0c, 0x02, 0x31, 0x85, 0x84, 0xb8, 0x58, 0xf2, 0x32, 0x93, 0xb3, 0x25, 0x98,
	0xc0, 0x42, 0x60, 0xb6, 0x90, 0x04, 0x17, 0x7b, 0x72, 0x46, 0x62, 0x5e, 0x5e, 0x6a, 0x8e, 0x04,
	0x33, 0x58, 0x18, 0xc6, 0x55, 0x32, 0x83, 0x99, 0x55, 0x5c, 0x00, 0xd2, 0x99, 0x9c, 0x9f, 0x92,
	0x0a, 0x36, 0x8c, 0x35, 0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x2b, 0x4a, 0x2d, 0x2e, 0xcd, 0x29,
	0x81, 0x9a, 0x07, 0xe5, 0x25, 0xb1, 0x81, 0xdd, 0x63, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xfc,
	0x01, 0xdd, 0x79, 0x9c, 0x00, 0x00, 0x00,
}
